### ISSUE TITLE
Custom component, uncomplete documentation 

### ISSUE THREAD

**Issue by MaximeConan** [untemps/react-vocal#29]
The documentation could detail the set of variables and methods we have access to when we decide to use a custom component.

**Comment by untemps** [comment]
You mean when using a function as component? Which variables do you need?

**Comment by MaximeConan** [comment]
I mean for this example from the doc : 

```
import Vocal from '@untemps/react-vocal'

const App = () => {
   return (
      <Vocal>{(start, stop) => (
         <div>
            <button onClick={start}>Start</button>
            <button onClick={stop}>Stop</button>
         </div>
      )}</Vocal>
   )
}
```

Is there a state `isListening` or `isActive` or something else to know if the vocal is currenlty listning ? So I could update the UI to match this state.
